[package]
name = "finder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
glob = "0.3.3"
grep = "0.3.2"
ignore = "0.4.23"
nucleo = "0.5.0"
skim = "0.20.5"
walkdir = "2.5.0"
