[package]
name = "finder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
crossterm = "0.29.0"
# glob = "0.3.3"
# grep = "0.3.2"
ignore = "0.4.23"
nucleo = "0.5.0"
